### ISSUE TITLE
Uncaught AttributeError: 'NoneType' object has no attribute 'format'


### ISSUE THREAD

**Issue by UrbanPlan-LDB** [florianneukirchen/qgis_adjust_style#8] opened 2023-06-08 08:36 UTC
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\qgis_adjust_style\adjust_style.py", line 279, in fontSizePlusBtn
    self.mapToLayers(self.layer_font_size)
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\qgis_adjust_style\adjust_style.py", line 393, in mapToLayers
    func(layer)
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\qgis_adjust_style\adjust_style.py", line 849, in layer_font_size
    settings = self.change_font_size(settings)
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\qgis_adjust_style\adjust_style.py", line 860, in change_font_size
    format = settings.format() # Returns QgsTextFormat
AttributeError: 'NoneType' object has no attribute 'format'

```
qgis_adjust_style 1.1, QGIS 3.30.3-'s-Hertogenbosch on Windows 10

**Comment by florianneukirchen** [comment] 2023-06-12 19:32
Thanks for reporting the issue. I could not reproduce the bug, but the git main branch should now catch the exception. Could you please test with your layer and the current git main?

**Comment by florianneukirchen** [comment] 2023-06-23 14:04
I really do not understand how you triggered the bug. It seems you have labels enabled (this is checked in line 581) on the layer in question, but without any label settings. I never have label settings of type None as soon as I switch on labels. 

Anyway, it should be fixed in git main now.

**Comment by florianneukirchen** [comment] 2023-06-26 06:33
Should be fixed in v.1.2, please reopen if you still get this issue.

**Comment by florianneukirchen** [comment] 2023-06-26 06:33
Should be fixed in v.1.2, please reopen if you still get this issue.

**Closed as completed by florianneukirchen** 2023-06-26 06:33 UTC
